version: "3.8"

services:
  vulnapp:
    build: ./vulnapp
    ports:
      - "5000:5000"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
